/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    name: 'Sencha',
    controllers: [
        'FormsController'
    ],

    launch: function() {
        var bd = Ext.getBody();

        bd.createChild({tag: 'h1', html: 'Dynamic Forms built with JavaScript'});

        bd.createChild({tag: 'h2', html: 'Form 1 - Very Simple'});

        Ext.create('Sencha.view.SimpleForm',{renderTo: bd});

        bd.createChild({tag: 'h2', html: 'Form 2 - Adding fieldsets'});

        Ext.create('Sencha.view.FieldSetForm',{renderTo: bd});

        bd.createChild({tag: 'h2', html: 'Form 3 - A little more complex'});

        Ext.create('Sencha.view.MultiColumnForm',{renderTo: bd});

        bd.createChild({tag: 'h2', html: 'Form 4 - Forms can be a TabPanel...'});

        Ext.create('Sencha.view.TabForm',{renderTo: bd});

        bd.createChild({tag: 'h2', html: 'Form 5 - ... and forms can contain TabPanel(s)'});

        Ext.create('Sencha.view.InnerTabsForm',{renderTo: bd});
    }

});
