/*
 * File: app/controller/UniqueField.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.UniqueField', {
    extend: 'Ext.app.Controller',

    views: [
        'RegisterWindow'
    ],

    onTextfieldBeforeRender: function(abstractcomponent, options) {
        abstractcomponent.vtype = 'uniqueUserName';
    },

    init: function() {
        this.control({
            "textfield[name='username']": {
                beforerender: this.onTextfieldBeforeRender
            }
        });

    }

});
