/*
 * File: app/controller/ForumSearch.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sencha.controller.ForumSearch', {
    extend: 'Ext.app.Controller',

    models: [
        'Post'
    ],
    stores: [
        'Posts'
    ],
    views: [
        'ForumSearch'
    ],

    onComboboxSelect: function(combo, records, options) {
        var post = records[0];
        if (post) {
            window.location =
            Ext.String.format('http://www.sencha.com/forum/showthread.php?t={0}&p={1}', post.get('topicId'), post.get('id'));
        }
    },

    init: function(application) {
        var body = Ext.getBody();
        var helper = new Ext.dom.Helper();

        var html = "<h1>Combo with Templates and Ajax</h1>";
        helper.append(body,html);

        html = "<p>This is a more advanced example that shows how you can combine ";
        html +="<!--paging, -->Ext.Template and a remote data store to create a ";
        html +="'live search' feature. Try searching for terms like 'form', or 'grid'.";
        helper.append(body,html);

        html = "<p>The js is not minified so it is readable. See <a href='app.js'>app.js</a>.</p>";
        helper.append(body,html);

        Ext.create('Sencha.view.ForumSearch',{
            renderTo: Ext.getBody()
        });

        this.control({
            "forumsearch combo[name=comboSearch]": {
                select: this.onComboboxSelect
            }
        });
    }

});
