/*
 * File: app/view/ForumSearch.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sencha.view.ForumSearch', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.forumsearch',

    width: 600,
    layout: {
        type: 'anchor'
    },
    bodyPadding: 10,
    title: 'Search the Ext Forums',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    listConfig: {
                        loadingText: 'Searching...',
                        emptyText: 'No matching posts found.',
                        // Custom rendering template for each item
                        getInnerTpl: function() {
                            return '<div class="search-item">' +
                                '<h3><span>{[Ext.Date.format(values.lastPost, "M j, Y")]}<br />by {author}</span>{title}</h3>' +
                                '{excerpt}' +
                            '</div>';
                        }
                    },
                    name: 'comboSearch',
                    hideLabel: true,
                    hideTrigger: true,
                    displayField: 'title',
                    pageSize: 10,
                    store: 'Posts',
                    typeAhead: false
                },
                {
                    xtype: 'component',
                    html: 'Live search requires a minimum of 4 characters.',
                    style: 'margin-top:10px'
                }
            ]
        });

        me.callParent(arguments);
    }

});