/*
 * File: app/view/CompanyGrid.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sencha.view.CompanyGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.companygrid',

    stateId: 'stateGrid',
    collapsible: true,
    title: 'Array Grid',
    store: 'Companies',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    sortable: false,
                    dataIndex: 'company',
                    flex: 1,
                    text: 'Company'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return Ext.util.Format.usMoney(value);
                    },
                    width: 75,
                    dataIndex: 'price',
                    text: 'Price'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        if (value > 0) {
                            return '<span style="color:green;">' + value + '</span>';
                        } else if (value < 0) {
                            return '<span style="color:red;">' + value + '</span>';
                        }
                        return value;
                    },
                    width: 75,
                    dataIndex: 'change',
                    text: 'Change'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        if (value > 0) {
                            return '<span style="color:green;">' + value + '%</span>';
                        } else if (value < 0) {
                            return '<span style="color:red;">' + value + '%</span>';
                        }
                        return value;
                    },
                    width: 75,
                    dataIndex: 'pctChange',
                    text: '% Change'
                },
                {
                    xtype: 'datecolumn',
                    width: 85,
                    dataIndex: 'lastChange',
                    text: 'Last Updated',
                    format: 'm/d/Y'
                },
                {
                    xtype: 'actioncolumn',
                    width: 50,
                    sortable: false,
                    menuDisabled: true,
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e) {
                                this.fireEvent('itemclick', this, 'sell', view, rowIndex, colIndex, item, e);
                            },
                            icon: '../../shared/icons/fam/delete.gif',
                            tooltip: 'Sell stock'
                        },
                        {
                            getClass: function(v, metadata, r, rowIndex, colIndex, store) {
                                if (r.get('change') < 0) {
                                    this.items[1].tooltip = 'Hold stock';
                                    return 'alert-col';
                                } else {
                                    this.items[1].tooltip = 'Buy stock';
                                    return 'buy-col';
                                }
                            },
                            handler: function(view, rowIndex, colIndex, item, e) {
                                var rec = view.getRecords(view.getNodes())[rowIndex];
                                var action = rec.get('change') < 0 ? 'hold' : 'buy';
                                this.fireEvent('itemclick', this, action, view, rowIndex, colIndex, item, e);
                            }
                        }
                    ]
                }
            ],
            viewConfig: {
                enableTextSelection: 'true'
            }
        });

        me.callParent(arguments);
    }

});