/*
 * File: app/view/module/Company.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExtDesktop.view.module.Company', {
    extend: 'Ext.ux.desktop.Module',

    requires: [
        'ExtDesktop.view.CompanyGrid'
    ],

    id: 'company-win',

    init: function() {
        this.launcher = {
            text: 'Companies List',
            iconCls:'tabs'
        };
    },

    createWindow: function() {
        var desktop = this.app.getDesktop();
        var win = desktop.getWindow('company-win');
        if(!win){
            win = desktop.createWindow({
                id: 'company-win',
                closeAction:'hide',
                title:'Companies List',
                width:500,
                height:400,

                layout:{
                        type:'fit'
                    },

                items:[{
                    xtype:'companygrid',
                    flex:1
                }]
            });
        }
        return win;
    }

});