/*
 * File: app/controller/GridPlugins.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sencha.controller.GridPlugins', {
    extend: 'Ext.app.Controller',

    models: [
        'Company'
    ],
    stores: [
        'Companies'
    ],
    views: [
        'GridRowExpander',
        'GridSelectionModel',
        'GridRowNumberer',
        'GridPanelToolbar'
    ],

    refs: [
        {
            ref: 'grid4',
            selector: 'grid4',
            xtype: 'grid4'
        }
    ],

    onGridpanelSelectionChange: function(tablepanel, selections, options) {
        this.getGrid4().down('#removeButton').setDisabled(selections.length == 0);
    },

    init: function(application) {
        this.control({
            "grid4": {
                selectionchange: this.onGridpanelSelectionChange
            }
        });
    }

});
