/*
 * File: app/store/Products.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sencha.store.Products', {
    extend: 'Ext.data.Store',

    requires: [
        'Sencha.model.Product'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoDestroy: true,
            storeId: 'Products',
            model: 'Sencha.model.Product',
            pageSize: 50,
            proxy: {
                type: 'ajax',
                url: 'data/grid-filter.json',
                reader: {
                    type: 'json',
                    idProperty: 'id',
                    root: 'data'
                }
            },
            sorters: {
                property: 'company'
            }
        }, cfg)]);
    }
});