/*
 * File: app/view/TermsOfUse.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sencha.view.TermsOfUse', {
    extend: 'Ext.window.Window',
    alias: 'widget.termsofuse',

    autoShow: true,
    height: 400,
    width: 700,
    autoScroll: true,
    bodyStyle: 'padding: 10px 20px;',
    title: 'Terms of Use',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            loader: {
                url: 'terms.html',
                autoLoad: true
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    ui: 'footer',
                    layout: {
                        pack: 'end',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            action: 'decline',
                            width: 70,
                            text: 'Decline'
                        },
                        {
                            xtype: 'button',
                            action: 'accept',
                            width: 70,
                            text: 'Accept'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});