/*
 * File: app/view/ForumThreadGrid.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sencha.view.ForumThreadGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.forumthreadgrid',

    requires: [
        'Ext.ux.PreviewPlugin'
    ],

    loadMask: true,
    height: 500,
    width: 700,
    title: 'ExtJS.com - Browse Forums',
    disableSelection: true,
    store: 'ForumThreads',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return Ext.String.format(
                        '<b><a href="http://sencha.com/forum/showthread.php?t={2}" target="_blank">{0}</a></b><a href="http://sencha.com/forum/forumdisplay.php?f={3}" target="_blank">{1} Forum</a>',
                        value,
                        record.data.forumtitle,
                        record.getId(),
                        record.data.forumid
                        );
                    },
                    id: 'topic',
                    sortable: false,
                    dataIndex: 'title',
                    flex: 1,
                    text: 'Topic'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    width: 100,
                    dataIndex: 'username',
                    text: 'Author'
                },
                {
                    xtype: 'gridcolumn',
                    width: 70,
                    dataIndex: 'replycount',
                    text: 'Replies'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return Ext.String.format('{0}<br/>by {1}', Ext.Date.dateFormat(value, 'M j, Y, g:i a'), record.get('lastposter'));
                    },
                    id: 'last',
                    width: 150,
                    dataIndex: 'lastpost',
                    text: 'Last Post'
                }
            ],
            viewConfig: {
                plugins: [
                    {
                        ptype: 'preview',
                        bodyField: 'excerpt',
                        expanded: true,
                        pluginId: 'preview'
                    }
                ],
                trackOver: false,
                stripeRows: false
            },
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    displayInfo: true,
                    displayMsg: 'Displaying topics {0} - {1} of {2}',
                    emptyMsg: 'No topics to display',
                    store: 'ForumThreads',
                    items: [
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            action: 'handlePreview',
                            enableToggle: true,
                            pressed: true,
                            text: 'Show Preview'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});