/*
 * File: app/view/ContainerFields.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sencha.view.ContainerFields', {
    extend: 'Ext.container.Container',
    alias: 'widget.containerFields',

    layout: {
        align: 'stretch',
        type: 'hbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'anchor'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '95%',
                            name: 'first',
                            value: 'Don',
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'First Name',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '95%',
                            name: 'company',
                            fieldLabel: 'Company'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'anchor'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'last',
                            value: 'Griffin',
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'Last Name',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'email',
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'Email',
                            allowBlank: false,
                            vtype: 'email'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});