/*
 * File: app/view/FieldSetForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sencha.view.FieldSetForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.fieldsetform',

    requires: [
        'Sencha.view.SaveCancelToolbar'
    ],

    frame: true,
    width: 350,
    bodyPadding: '5 5 0',
    collapsible: true,
    title: 'Simple Form with FieldSets',
    url: 'save-form.php',

    initComponent: function() {
        var me = this;

        me.initialConfig = Ext.apply({
            url: 'save-form.php'
        }, me.initialConfig);

        Ext.applyIf(me, {
            defaults: {
                anchor: '100%',
                msgTarget: 'side',
                labelWidth: 75
            },
            items: [
                {
                    xtype: 'fieldset',
                    defaults: {
                        anchor: '100%'
                    },
                    checkboxToggle: true,
                    collapsed: true,
                    title: 'User Information',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'first',
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'First Name',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'last',
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'Last Name'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'company',
                            fieldLabel: 'Company'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'email',
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'Email',
                            vtype: 'email'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    defaults: {
                        anchor: '100%'
                    },
                    collapsible: true,
                    title: 'Phone Number',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'home',
                            value: '(888) 555-1212',
                            fieldLabel: 'Home'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'business',
                            fieldLabel: 'Business'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'mobile',
                            fieldLabel: 'Mobile'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'fax',
                            fieldLabel: 'Fax'
                        }
                    ]
                },
                {
                    xtype: 'savecanceltoolbar'
                }
            ]
        });

        me.callParent(arguments);
    }

});