/*
 * File: app/view/InnerTabsForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sencha.view.InnerTabsForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.innertabsform',

    requires: [
        'Sencha.view.SaveCancelToolbar'
    ],

    width: 600,
    bodyPadding: 5,
    collapsible: true,
    title: 'Inner Tabs',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            fieldDefaults: {
                labelAlign: 'top',
                msgTarget: 'side'
            },
            items: [
                {
                    xtype: 'container',
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'anchor'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '95%',
                                    name: 'first',
                                    afterLabelTextTpl: [
                                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                    ],
                                    fieldLabel: 'First Name',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '95%',
                                    name: 'company',
                                    fieldLabel: 'Company'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'anchor'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    name: 'last',
                                    afterLabelTextTpl: [
                                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                    ],
                                    fieldLabel: 'Last Name',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    name: 'email',
                                    afterLabelTextTpl: [
                                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                    ],
                                    fieldLabel: 'Email',
                                    allowBlank: false,
                                    vtype: 'email'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    height: 235,
                    defaults: {
                        bodyPadding: 10
                    },
                    activeTab: 0,
                    plain: true,
                    items: [
                        {
                            xtype: 'panel',
                            defaults: {
                                width: 230
                            },
                            title: 'Personal Details',
                            items: [
                                {
                                    xtype: 'textfield',
                                    name: 'first',
                                    value: 'Jaime',
                                    afterLabelTextTpl: [
                                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                    ],
                                    fieldLabel: 'First Name',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'last',
                                    value: 'Avins',
                                    afterLabelTextTpl: [
                                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                    ],
                                    fieldLabel: 'Last Name',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'company',
                                    value: 'Ext JS',
                                    fieldLabel: 'Company'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'email',
                                    afterLabelTextTpl: [
                                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                    ],
                                    fieldLabel: 'Email',
                                    allowBlank: false,
                                    vtype: 'email'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            defaults: {
                                width: 230
                            },
                            title: 'Phone Numbers',
                            items: [
                                {
                                    xtype: 'textfield',
                                    name: 'home',
                                    value: '(888) 555-1212',
                                    fieldLabel: 'Home'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'business',
                                    fieldLabel: 'Business'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'mobile',
                                    fieldLabel: 'Mobile'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'fax',
                                    fieldLabel: 'Fax'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            cls: 'x-plain',
                            layout: {
                                type: 'fit'
                            },
                            title: 'Biography',
                            items: [
                                {
                                    xtype: 'htmleditor',
                                    name: 'bio2',
                                    fieldLabel: 'Biography'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'savecanceltoolbar'
                }
            ]
        });

        me.callParent(arguments);
    }

});