/*
 * File: app/view/MultiColumnForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sencha.view.MultiColumnForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.multicolumnform',

    requires: [
        'Sencha.view.ContainerFields',
        'Sencha.view.SaveCancelToolbar'
    ],

    frame: true,
    width: 600,
    bodyPadding: '5 5 0',
    collapsible: true,
    title: 'Multi Column, Nested Layouts and Anchoring',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            fieldDefaults: {
                labelAlign: 'top',
                msgTarget: 'side'
            },
            items: [
                {
                    xtype: 'containerFields',
                    anchor: '100%'
                },
                {
                    xtype: 'htmleditor',
                    anchor: '100%',
                    height: 200,
                    name: 'bio',
                    fieldLabel: 'Biography'
                },
                {
                    xtype: 'savecanceltoolbar'
                }
            ]
        });

        me.callParent(arguments);
    }

});