/*
 * File: app/view/SaveCancelToolbar.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sencha.view.SaveCancelToolbar', {
    extend: 'Ext.toolbar.Toolbar',
    alias: 'widget.savecanceltoolbar',

    ui: 'footer',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            layout: {
                pack: 'end',
                type: 'hbox'
            },
            items: [
                {
                    xtype: 'button',
                    action: 'save',
                    width: 80,
                    text: 'Save'
                },
                {
                    xtype: 'button',
                    action: 'cancel',
                    width: 80,
                    text: 'Cancel'
                }
            ]
        });

        me.callParent(arguments);
    }

});