/*
 * File: app/view/TabForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sencha.view.TabForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.tabform',

    requires: [
        'Sencha.view.SaveCancelToolbar'
    ],

    border: false,
    width: 350,
    bodyBorder: false,
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            fieldDefaults: {
                labelWidth: 75,
                msgTarget: 'side'
            },
            items: [
                {
                    xtype: 'tabpanel',
                    defaults: {
                        bodyPadding: 10,
                        layout: 'anchor'
                    },
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            defaults: {
                                anchor: '100%'
                            },
                            title: 'Personal Details',
                            items: [
                                {
                                    xtype: 'textfield',
                                    name: 'first',
                                    value: 'Ed',
                                    afterLabelTextTpl: [
                                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                    ],
                                    fieldLabel: 'First Name',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'last',
                                    value: 'Spencer',
                                    afterLabelTextTpl: [
                                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                    ],
                                    fieldLabel: 'Last Name',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'company',
                                    value: 'Ext JS',
                                    fieldLabel: 'Company'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'email',
                                    afterLabelTextTpl: [
                                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                    ],
                                    fieldLabel: 'Email',
                                    allowBlank: false,
                                    vtype: 'email'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            defaults: {
                                anchor: '100%'
                            },
                            title: 'Phone Numbers',
                            items: [
                                {
                                    xtype: 'textfield',
                                    name: 'home',
                                    value: '(888) 555-1212',
                                    fieldLabel: 'Home'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'business',
                                    fieldLabel: 'Business'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'mobile',
                                    fieldLabel: 'Mobile'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'fax',
                                    fieldLabel: 'Fax'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'savecanceltoolbar'
                }
            ]
        });

        me.callParent(arguments);
    }

});