/*
 * File: app/view/MyForm.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sencha.view.MyForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.myform',

    height: 250,
    width: 400,
    bodyPadding: 10,
    title: 'My Form',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'radiofield',
                    anchor: '100%',
                    fieldLabel: 'Label',
                    boxLabel: 'Box Label'
                },
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'htmleditor',
                    anchor: '100%',
                    height: 150,
                    fieldLabel: 'Label'
                }
            ]
        });

        me.callParent(arguments);
    }

});