/*
 * File: app/view/ProductGridPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sencha.view.ProductGridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.productgridpanel',

    requires: [
        'Sencha.view.override.ProductGridPanel',
        'Ext.ux.grid.FiltersFeature'
    ],

    border: false,
    height: 250,
    width: 400,
    store: 'Products',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {

            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    filterable: true,
                    width: 30,
                    dataIndex: 'id',
                    text: 'Id'
                },
                {
                    xtype: 'gridcolumn',
                    filter: {
                        type: 'string'
                    },
                    dataIndex: 'company',
                    flex: 1,
                    text: 'Company'
                },
                {
                    xtype: 'numbercolumn',
                    filter: {
                        //type: 'numeric'  // specify type here or in store fields config
                    },
                    width: 70,
                    dataIndex: 'price',
                    text: 'Price'
                },
                {
                    xtype: 'gridcolumn',
                    filter: {
                        type: 'list',
                        options: [
                            'small',
                            'medium',
                            'large',
                            'extra large'
                        ]
                    },
                    dataIndex: 'size',
                    text: 'Size'
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    displayInfo: true,
                    store: 'Products',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            itemId: 'encode',
                            enableToggle: true,
                            text: 'Encode: Off',
                            tooltip: 'Toggle Filter encoding on/off'
                        },
                        {
                            xtype: 'button',
                            itemId: 'localFiltering',
                            enableToggle: true,
                            text: 'Local Filtering: On',
                            tooltip: 'Toggle Filtering between remote/local'
                        },
                        {
                            xtype: 'button',
                            itemId: 'filterData',
                            text: 'All Filter Data',
                            tooltip: 'Get Filter Data for Grid'
                        },
                        {
                            xtype: 'button',
                            itemId: 'clearFilter',
                            text: 'Clear Filter Data'
                        },
                        {
                            xtype: 'button',
                            itemId: 'addColumns',
                            text: 'Add Columns'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});