/*
 * File: app/model/Post.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sencha.model.Post', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'id',
            mapping: 'post_id'
        },
        {
            name: 'title',
            mapping: 'topic_title'
        },
        {
            name: 'topicId',
            mapping: 'topic_id'
        },
        {
            name: 'author',
            mapping: 'author'
        },
        {
            name: 'lastPost',
            dateFormat: 'timestamp',
            mapping: 'post_time',
            type: 'date'
        },
        {
            name: 'excerpt',
            mapping: 'post_text'
        }
    ]
});