/*
 * File: app/view/Desktop.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExtDesktop.view.Desktop', {
    extend: 'Ext.ux.desktop.App',
    alias: 'widget.mydesktop',

    requires: [
        'Ext.window.MessageBox',
        'Ext.ux.desktop.ShortcutModel'
    ],

    init: function() {
        this.callParent();
    },

    onSettings: function() {
        Ext.widget('window',{
            title: 'Settings',
            width: 200,
            height: 200
        }).show();
    },

    getModules: function() {
        var priv = {
            modules:[
                'ExtDesktop.view.module.Company'
                ],
            shortcuts:[{ name: 'Companies List', iconCls: 'grid-shortcut', module: 'company-win' }]
        };

        var modules = priv.modules;

        var modulesAux = [];

        Ext.each(modules, function(item) {
            modulesAux.push(Ext.create(item));
        }, this);

        return modulesAux;
    },

    getDesktopConfig: function() {
        var me = this, ret = me.callParent();

        var priv = {
            modules:[
                'ExtDesktop.view.module.Company'
                ],
            shortcuts:[{ name: 'Companies List', iconCls: 'grid-shortcut', module: 'company-win' }]
        };

        return Ext.apply(ret, {

            contextMenuItems: [
                { text: 'Change Settings', handler: me.onSettings, scope: me }
            ],

            shortcuts: Ext.create('Ext.data.Store', {
                model: 'Ext.ux.desktop.ShortcutModel',
                data: priv.shortcuts
            }),

            wallpaper: 'resources/wallpapers/Blue-Sencha.jpg',
            wallpaperStretch: false
        });
    },

    getStartConfig: function() {
        var me = this, ret = me.callParent();

        return Ext.apply(ret, {
            title: 'Loiane Groner',
            iconCls: 'user',
            height: 300,
            toolConfig: {
                width: 100,
                items: [
                    {
                        text:'Settings',
                        iconCls:'settings',
                        handler: me.onSettings,
                        scope: me
                    },
                    '-',
                    {
                        text:'Logout',
                        iconCls:'logout',
                        handler: me.onLogout,
                        scope: me
                    }
                ]
            }
        });
    },

    getTaskbarConfig: function() {
        var ret = this.callParent();

        return Ext.apply(ret, {
            quickStart: [
                { name: 'Grid Window', iconCls: 'icon-grid', module: 'company-win' }
            ],
            trayItems: [
                { xtype: 'trayclock', flex: 1 }
            ]
        });
    },

    onLogout: function() {
        Ext.Msg.confirm('Logout', 'Are you sure you want to logout?');
    }

});